# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/incident.proto

require 'google/protobuf'

require 'riot_api/message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.Incident" do
    optional :active, :bool, 1
    optional :created_at, :string, 2
    optional :id, :string, 4
    repeated :updates, :message, 5, "riotAPI.Message"
  end
end

module RiotAPI
  Incident = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.Incident").msgclass
end
