# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/message.proto

require 'google/protobuf'

require 'riot_api/translation_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.Message" do
    optional :author, :string, 1
    optional :content, :string, 2
    optional :created_at, :string, 3
    optional :id, :string, 4
    optional :severity, :string, 5
    repeated :translations, :message, 6, "riotAPI.Translation"
    optional :updated_at, :string, 7
  end
end

module RiotAPI
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.Message").msgclass
end
