# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/protocols.proto

require 'google/protobuf'

require 'riot_api/status/region_pb'
require 'riot_api/status/service_pb'
require 'riot_api/status/message_pb'
require 'riot_api/status/translation_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module RiotAPI
end
