# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/protocols.proto

require 'google/protobuf'

require 'riot_api/region_pb'
require 'riot_api/service_pb'
require 'riot_api/message_pb'
require 'riot_api/translation_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module RiotAPI
end
