# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/service.proto

require 'google/protobuf'

require 'riot_api/incident_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.Service" do
    repeated :incidents, :message, 1, "riotAPI.Incident"
    optional :name, :string, 2
    optional :slug, :string, 3
    optional :status, :string, 4
  end
end

module RiotAPI
  Service = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.Service").msgclass
end
