# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/translation.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.Translation" do
    optional :content, :string, 1
    optional :locale, :string, 2
    optional :updated_at, :string, 3
    optional :heading, :string, 4
  end
end

module RiotAPI
  Translation = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.Translation").msgclass
end
