
# Available ruby versions: http://rubies.travis-ci.org/

language: ruby
os:
  - linux
  - osx
rvm:
  - "2.0"
  - "2.1" # latest 2.1.x
  - "2.2" # latest 2.2.x
  - "2.3" # latest 2.3.x
  - "ruby-head"
script:
  bundle exec rake test
branches:
  except:
    - "readme-edits"

# Travis OS X support is pretty janky. These are some hacks to include tests
# only on versions that actually work.
# (last tested: 2016-04)
matrix:
  exclude:
    - os: osx
      rvm: '2.2'
#    - os: osx
#      rvm: '2.3.1' # No 2.3.x at all
#  include:
#    - os: osx
#      rvm: '2.2' # Travis OS X doesn't have 2.2 aliases
  allow_failures:
    - rvm: 'ruby-head'
  fast_finish: true

sudo: false