# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/status/incident.proto

require 'google/protobuf'

require 'riot_api/status/message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.status.Incident" do
    optional :active, :bool, 1
    optional :created_at, :string, 2
    optional :id, :string, 4
    repeated :updates, :message, 5, "riotAPI.status.Message"
  end
end

module RiotAPI
  module Status
    Incident = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.status.Incident").msgclass
  end
end
