# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riot_api/status/service.proto

require 'google/protobuf'

require 'riot_api/status/incident_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.status.Service" do
    repeated :incidents, :message, 1, "riotAPI.status.Incident"
    optional :name, :string, 2
    optional :slug, :string, 3
    optional :status, :string, 4
  end
end

module RiotAPI
  module Status
    Service = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.status.Service").msgclass
  end
end
